"""
Compare raw Ultralytics ByteTrack vs BoT-SORT IDs before TrackletManager.

The output video shows two panels side by side. IDs drawn on each panel are the
raw IDs returned by model.track(), not the global IDs from src/tracking.py.
"""

import argparse
import csv
import collections
import json
import os
import tempfile
import time
from pathlib import Path

import cv2
import numpy as np
from ultralytics import YOLO

from tracking import CFG, _get_runtime_config


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_VIDEO = ROOT / "assets" / "ps_Long" / "1_2026-04-23_144019.mp4"
DEFAULT_OUTPUT = ROOT / "assets" / "video_results" / "difference_bytetrack_vs_botsort_19.mp4"
DEFAULT_REPORT_DIR = ROOT / "assets" / "tracker_compare_reports"
COMMON_TRACKER_PARAMS = {
    "track_high_thresh": 0.55,
    "track_low_thresh": 0.10,
    "new_track_thresh": 0.60,
    "track_buffer": 240,
    "match_thresh": 0.80,
    "fuse_score": True,
}
BOTSORT_EXTRA_PARAMS = {
    "gmc_method": None,
    "proximity_thresh": 0.50,
    "appearance_thresh": 0.45,
    "with_reid": True,
    "model": "auto",
}

PALETTE = [
    (255, 80, 80), (80, 200, 80), (80, 80, 255), (255, 200, 0),
    (200, 0, 255), (0, 200, 255), (255, 128, 0), (128, 255, 0),
    (0, 128, 255), (255, 0, 128), (0, 255, 128), (128, 0, 255),
]


def parse_args():
    parser = argparse.ArgumentParser(
        description="Visual compare raw ByteTrack and BoT-SORT person tracking IDs."
    )
    parser.add_argument("--video", default=str(DEFAULT_VIDEO), help="Input video path.")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="Output mp4 path.")
    parser.add_argument("--model", default=CFG["yolo_model"], help="YOLO model path/name.")
    parser.add_argument("--device", default=CFG["device"], help="Device: auto, cpu, cuda, cuda:0, or 0.")
    parser.add_argument(
        "--allow-cpu-fallback",
        action="store_true",
        help="Allow CPU fallback if CUDA is not available.",
    )
    parser.add_argument("--conf", type=float, default=0.25, help="YOLO detection confidence.")
    parser.add_argument("--iou", type=float, default=CFG["iou_thresh"], help="YOLO NMS IoU.")
    parser.add_argument("--imgsz", type=int, default=CFG["imgsz"], help="YOLO image size.")
    parser.add_argument(
        "--max-frames",
        type=int,
        default=0,
        help="Stop after this many frames. 0 means full video.",
    )
    parser.add_argument(
        "--scale",
        type=float,
        default=0.5,
        help="Scale each panel before writing side-by-side output.",
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Show live comparison window when DISPLAY is available.",
    )
    parser.add_argument(
        "--report-dir",
        default=str(DEFAULT_REPORT_DIR),
        help="Directory for metrics.csv, summary.md, and snapshot images.",
    )
    parser.add_argument(
        "--snapshot-interval",
        type=int,
        default=0,
        help="Save one side-by-side image every N frames. 0 disables snapshots.",
    )
    parser.add_argument(
        "--short-track-frames",
        type=int,
        default=15,
        help="Tracks with <= this many observed frames are counted as short tracks.",
    )
    parser.add_argument(
        "--fixed-order",
        action="store_true",
        help="Always run ByteTrack before BoT-SORT. Default alternates order per frame.",
    )
    return parser.parse_args()


def yaml_value(value):
    if isinstance(value, bool):
        return "True" if value else "False"
    if value is None:
        return "None"
    return str(value)


def tracker_yaml(tracker_type):
    if tracker_type not in {"bytetrack", "botsort"}:
        raise ValueError(f"Unsupported tracker_type: {tracker_type}")

    params = {"tracker_type": tracker_type, **COMMON_TRACKER_PARAMS}
    if tracker_type == "botsort":
        params.update(BOTSORT_EXTRA_PARAMS)

    lines = [
        "# Generated by src/difference.py",
        "# Common params are identical for ByteTrack and BoT-SORT.",
    ]
    if tracker_type == "botsort":
        lines.append("# BoT-SORT-only ReID/GMC features are enabled below.")
    else:
        lines.append("# ByteTrack has no ReID/GMC block in Ultralytics.")
    lines.extend(f"{key}: {yaml_value(value)}" for key, value in params.items())
    return "\n".join(lines) + "\n"


def write_tracker_cfgs(tmp_dir):
    cfgs = {}
    for name in ("bytetrack", "botsort"):
        path = Path(tmp_dir) / f"{name}.yaml"
        path.write_text(tracker_yaml(name), encoding="utf-8")
        cfgs[name] = str(path)
    return cfgs


def color_for(track_id):
    return PALETTE[int(track_id) % len(PALETTE)]


def draw_label(frame, text, x, y, color, font_scale=0.55):
    (tw, th), _ = cv2.getTextSize(text, cv2.FONT_HERSHEY_SIMPLEX, font_scale, 1)
    x = max(0, min(x, frame.shape[1] - tw - 4))
    y = max(th + 8, min(y, frame.shape[0] - 2))
    cv2.rectangle(frame, (x, y - th - 8), (x + tw + 4, y), color, -1)
    cv2.putText(
        frame,
        text,
        (x + 2, y - 4),
        cv2.FONT_HERSHEY_SIMPLEX,
        font_scale,
        (0, 0, 0),
        1,
        cv2.LINE_AA,
    )


def draw_tracks(frame, result, title, frame_idx, fps_val, seen_ids):
    panel = frame.copy()
    active_ids = set()

    if result.boxes is not None and result.boxes.id is not None:
        boxes = result.boxes.xyxy.detach().cpu().numpy()
        ids = result.boxes.id.int().detach().cpu().numpy()
        confs = result.boxes.conf.detach().cpu().numpy()

        for box, track_id, conf in zip(boxes, ids, confs):
            track_id = int(track_id)
            active_ids.add(track_id)
            seen_ids.add(track_id)
            x1, y1, x2, y2 = [int(v) for v in box]
            color = color_for(track_id)
            cv2.rectangle(panel, (x1, y1), (x2, y2), color, 2, cv2.LINE_AA)
            draw_label(panel, f"ID:{track_id} c:{conf:.2f}", x1, y1, color)

    overlay = panel.copy()
    cv2.rectangle(overlay, (0, 0), (430, 116), (20, 20, 20), -1)
    cv2.addWeighted(overlay, 0.65, panel, 0.35, 0, panel)
    lines = [
        title,
        f"Frame: {frame_idx}",
        f"FPS: {fps_val:.1f}",
        f"Active raw IDs: {len(active_ids)}",
        f"Total unique raw IDs: {len(seen_ids)}",
    ]
    for idx, line in enumerate(lines):
        font_scale = 0.70 if idx == 0 else 0.55
        color = (240, 240, 240) if idx == 0 else (200, 240, 200)
        cv2.putText(
            panel,
            line,
            (10, 24 + idx * 21),
            cv2.FONT_HERSHEY_SIMPLEX,
            font_scale,
            color,
            1,
            cv2.LINE_AA,
        )
    return panel, active_ids


def resize_panel(frame, scale):
    if abs(scale - 1.0) < 1e-6:
        return frame
    width = max(1, int(frame.shape[1] * scale))
    height = max(1, int(frame.shape[0] * scale))
    return cv2.resize(frame, (width, height), interpolation=cv2.INTER_AREA)


def run_tracker(model, frame, tracker_cfg, args, yolo_device, use_half):
    return model.track(
        source=frame,
        persist=True,
        tracker=tracker_cfg,
        classes=[0],
        conf=args.conf,
        iou=args.iou,
        imgsz=args.imgsz,
        half=use_half,
        device=yolo_device,
        verbose=False,
    )[0]


def draw_bar_chart(canvas, origin, size, labels, values, colors, title, lower_is_better):
    x0, y0 = origin
    width, height = size
    chart_pad = 44
    plot_x = x0 + chart_pad
    plot_y = y0 + 74
    plot_w = width - chart_pad * 2
    plot_h = height - 134
    max_value = max(max(values), 1.0)

    cv2.rectangle(canvas, (x0, y0), (x0 + width, y0 + height), (255, 255, 255), -1)
    cv2.rectangle(canvas, (x0, y0), (x0 + width, y0 + height), (217, 226, 236), 2)
    cv2.putText(
        canvas,
        title,
        (x0 + 24, y0 + 38),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.78,
        (31, 41, 51),
        2,
        cv2.LINE_AA,
    )
    cv2.putText(
        canvas,
        "Lower is better" if lower_is_better else "Higher is better",
        (x0 + 24, y0 + 64),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.48,
        (82, 96, 109),
        1,
        cv2.LINE_AA,
    )

    cv2.line(canvas, (plot_x, plot_y + plot_h), (plot_x + plot_w, plot_y + plot_h), (203, 210, 217), 2)
    bar_w = int(plot_w * 0.22)
    gap = int(plot_w * 0.22)
    start_x = plot_x + int(plot_w * 0.18)
    for idx, (label, value, color) in enumerate(zip(labels, values, colors)):
        bar_h = int((value / max_value) * max(plot_h - 20, 1))
        bx = start_x + idx * (bar_w + gap)
        by = plot_y + plot_h - bar_h
        cv2.rectangle(canvas, (bx, by), (bx + bar_w, plot_y + plot_h), color, -1)
        cv2.putText(
            canvas,
            f"{value:.1f}" if isinstance(value, float) and not value.is_integer() else str(int(value)),
            (bx + 6, max(by - 12, plot_y + 18)),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.72,
            (31, 41, 51),
            2,
            cv2.LINE_AA,
        )
        cv2.putText(
            canvas,
            label,
            (bx - 10, plot_y + plot_h + 32),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.58,
            (31, 41, 51),
            2,
            cv2.LINE_AA,
        )


def write_simple_chart(report_dir, summary):
    chart_path = report_dir / "comparison_chart.png"
    byte = summary["trackers"]["bytetrack"]
    bot = summary["trackers"]["botsort"]
    labels = ["ByteTrack", "BoT-SORT"]
    colors = [(47, 128, 237), (235, 87, 87)]

    canvas = np.full((1080, 1600, 3), 247, dtype=np.uint8)
    cv2.putText(
        canvas,
        "ByteTrack vs BoT-SORT - Simple Comparison",
        (60, 78),
        cv2.FONT_HERSHEY_SIMPLEX,
        1.35,
        (31, 41, 51),
        3,
        cv2.LINE_AA,
    )
    cv2.putText(
        canvas,
        f"Video: {summary['frames']} frames | Raw tracker IDs before post-processing",
        (62, 124),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.72,
        (82, 96, 109),
        2,
        cv2.LINE_AA,
    )

    cards = [
        ("Raw IDs", f"{byte['unique_ids']} vs {bot['unique_ids']}", "Lower means less ID fragmentation"),
        ("Short tracks", f"{byte['short_tracks']} vs {bot['short_tracks']}", "Lower means fewer unstable IDs"),
        ("Avg FPS", f"{byte['avg_fps']:.1f} vs {bot['avg_fps']:.1f}", "Higher means faster processing"),
    ]
    for idx, (title, value, note) in enumerate(cards):
        x = 60 + idx * 500
        y = 160
        cv2.rectangle(canvas, (x, y), (x + 440, y + 118), (255, 255, 255), -1)
        cv2.rectangle(canvas, (x, y), (x + 440, y + 118), (217, 226, 236), 2)
        cv2.putText(canvas, title, (x + 24, y + 34), cv2.FONT_HERSHEY_SIMPLEX, 0.64, (82, 96, 109), 2, cv2.LINE_AA)
        cv2.putText(canvas, value, (x + 24, y + 76), cv2.FONT_HERSHEY_SIMPLEX, 1.08, (31, 41, 51), 3, cv2.LINE_AA)
        cv2.putText(canvas, note, (x + 24, y + 102), cv2.FONT_HERSHEY_SIMPLEX, 0.45, (123, 135, 148), 1, cv2.LINE_AA)

    draw_bar_chart(
        canvas,
        (60, 330),
        (470, 520),
        labels,
        [byte["unique_ids"], bot["unique_ids"]],
        colors,
        "Total Raw IDs",
        lower_is_better=True,
    )
    draw_bar_chart(
        canvas,
        (565, 330),
        (470, 520),
        labels,
        [byte["short_tracks"], bot["short_tracks"]],
        colors,
        "Short Tracks",
        lower_is_better=True,
    )
    draw_bar_chart(
        canvas,
        (1070, 330),
        (470, 520),
        labels,
        [byte["avg_fps"], bot["avg_fps"]],
        colors,
        "Average FPS",
        lower_is_better=False,
    )

    if byte["unique_ids"] <= bot["unique_ids"] and byte["avg_fps"] > bot["avg_fps"]:
        conclusion = "Conclusion: ByteTrack is faster, while BoT-SORT does not reduce raw ID count on this run."
    elif bot["unique_ids"] < byte["unique_ids"]:
        conclusion = "Conclusion: BoT-SORT reduces raw ID count, but speed trade-off should be checked."
    else:
        conclusion = "Conclusion: Compare raw IDs and FPS together before choosing the tracker."
    cv2.putText(canvas, conclusion, (60, 940), cv2.FONT_HERSHEY_SIMPLEX, 0.78, (31, 41, 51), 2, cv2.LINE_AA)
    cv2.putText(
        canvas,
        "Note: true accuracy requires manually labeled ground truth; this chart uses simple ID-stability indicators.",
        (60, 980),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.56,
        (82, 96, 109),
        1,
        cv2.LINE_AA,
    )
    cv2.imwrite(str(chart_path), canvas)
    return chart_path


def extract_tracks(result):
    tracks = []
    if result.boxes is None or result.boxes.id is None:
        return tracks

    boxes = result.boxes.xyxy.detach().cpu().numpy()
    ids = result.boxes.id.int().detach().cpu().numpy()
    confs = result.boxes.conf.detach().cpu().numpy()
    for box, track_id, conf in zip(boxes, ids, confs):
        tracks.append({
            "id": int(track_id),
            "box": [float(v) for v in box],
            "conf": float(conf),
        })
    return tracks


class TrackerStats:
    def __init__(self, name, short_track_frames=15):
        self.name = name
        self.short_track_frames = short_track_frames
        self.frames = 0
        self.seen_ids = set()
        self.prev_active_ids = set()
        self.active_counts = []
        self.detection_counts = []
        self.latencies = []
        self.conf_values = []
        self.new_id_events = 0
        self.lost_id_events = 0
        self.reappeared_id_events = 0
        self.track_frames = collections.defaultdict(int)
        self.track_first_frame = {}
        self.track_last_frame = {}
        self.track_gap_events = collections.defaultdict(int)

    def update(self, frame_idx, tracks, latency_sec):
        active_ids = {track["id"] for track in tracks}
        new_ids = active_ids - self.seen_ids
        lost_ids = self.prev_active_ids - active_ids
        reappeared_ids = (active_ids & self.seen_ids) - self.prev_active_ids

        self.frames += 1
        self.new_id_events += len(new_ids)
        self.lost_id_events += len(lost_ids)
        self.reappeared_id_events += len(reappeared_ids)
        self.active_counts.append(len(active_ids))
        self.detection_counts.append(len(tracks))
        self.latencies.append(float(latency_sec))

        for track in tracks:
            track_id = track["id"]
            self.seen_ids.add(track_id)
            self.track_frames[track_id] += 1
            self.track_first_frame.setdefault(track_id, frame_idx)
            previous_last = self.track_last_frame.get(track_id)
            if previous_last is not None and frame_idx - previous_last > 1:
                self.track_gap_events[track_id] += 1
            self.track_last_frame[track_id] = frame_idx
            self.conf_values.append(track["conf"])

        self.prev_active_ids = active_ids

    def _mean(self, values):
        return float(np.mean(values)) if values else 0.0

    def _median(self, values):
        return float(np.median(values)) if values else 0.0

    def _p95(self, values):
        return float(np.percentile(values, 95)) if values else 0.0

    def summary(self):
        track_lengths = list(self.track_frames.values())
        avg_active = self._mean(self.active_counts)
        unique_ids = len(self.seen_ids)
        total_latency = sum(self.latencies)
        return {
            "name": self.name,
            "frames": self.frames,
            "unique_ids": unique_ids,
            "avg_active_ids": avg_active,
            "max_active_ids": max(self.active_counts) if self.active_counts else 0,
            "avg_detections_per_frame": self._mean(self.detection_counts),
            "new_id_events": self.new_id_events,
            "lost_id_events": self.lost_id_events,
            "reappeared_id_events": self.reappeared_id_events,
            "gap_events": int(sum(self.track_gap_events.values())),
            "short_tracks": int(sum(1 for length in track_lengths if length <= self.short_track_frames)),
            "avg_track_observed_frames": self._mean(track_lengths),
            "median_track_observed_frames": self._median(track_lengths),
            "avg_confidence": self._mean(self.conf_values),
            "avg_fps": self.frames / max(total_latency, 1e-6),
            "avg_latency_ms": self._mean(self.latencies) * 1000.0,
            "median_latency_ms": self._median(self.latencies) * 1000.0,
            "p95_latency_ms": self._p95(self.latencies) * 1000.0,
            "id_fragmentation_proxy": unique_ids / max(avg_active, 1e-6),
        }

    def track_rows(self):
        rows = []
        for track_id in sorted(self.track_frames):
            rows.append({
                "tracker": self.name,
                "raw_id": track_id,
                "first_frame": self.track_first_frame.get(track_id, ""),
                "last_frame": self.track_last_frame.get(track_id, ""),
                "observed_frames": self.track_frames[track_id],
                "gap_events": self.track_gap_events.get(track_id, 0),
            })
        return rows


def write_report_files(report_dir, rows, summary):
    report_dir.mkdir(parents=True, exist_ok=True)
    metrics_path = report_dir / "metrics.csv"
    summary_path = report_dir / "summary.md"
    tracks_path = report_dir / "track_lifetimes.csv"

    with metrics_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "frame",
                "bytetrack_active_ids",
                "botsort_active_ids",
                "bytetrack_unique_ids",
                "botsort_unique_ids",
                "bytetrack_fps_rolling",
                "botsort_fps_rolling",
                "bytetrack_new_id_events",
                "botsort_new_id_events",
                "bytetrack_lost_id_events",
                "botsort_lost_id_events",
                "bytetrack_reappeared_id_events",
                "botsort_reappeared_id_events",
                "bytetrack_latency_ms",
                "botsort_latency_ms",
            ],
        )
        writer.writeheader()
        writer.writerows(rows)

    json_path = report_dir / "summary.json"
    json_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    chart_path = write_simple_chart(report_dir, summary)

    with tracks_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "tracker",
                "raw_id",
                "first_frame",
                "last_frame",
                "observed_frames",
                "gap_events",
            ],
        )
        writer.writeheader()
        writer.writerows(summary["track_lifetimes"])

    byte = summary["trackers"]["bytetrack"]
    bot = summary["trackers"]["botsort"]
    if byte["unique_ids"] <= bot["unique_ids"] and byte["avg_fps"] > bot["avg_fps"]:
        conclusion = (
            "ByteTrack is faster, while BoT-SORT does not reduce raw ID count "
            "in this run."
        )
    elif bot["unique_ids"] < byte["unique_ids"]:
        conclusion = (
            "BoT-SORT reduces raw ID count, but the speed trade-off should be "
            "reviewed before replacing ByteTrack."
        )
    else:
        conclusion = "Both trackers should be compared using raw IDs and FPS together."
    lines = [
        "# ByteTrack vs BoT-SORT Comparison Summary",
        "",
        "## Result",
        "",
        f"**Conclusion:** {conclusion}",
        "",
        "| Metric | ByteTrack | BoT-SORT | Meaning |",
        "|---|---:|---:|---|",
        f"| Total raw IDs | {byte['unique_ids']} | {bot['unique_ids']} | Lower is better |",
        f"| Short tracks | {byte['short_tracks']} | {bot['short_tracks']} | Lower is better |",
        f"| Average FPS | {byte['avg_fps']:.1f} | {bot['avg_fps']:.1f} | Higher is better |",
        f"| Average latency | {byte['avg_latency_ms']:.1f} ms | {bot['avg_latency_ms']:.1f} ms | Lower is better |",
        "",
        "## Files",
        "",
        f"- Chart: `{chart_path}`",
        f"- Output video: `{summary['output']}`",
        f"- Detailed CSV: `{metrics_path}`",
        f"- Summary JSON: `{json_path}`",
        "",
        "Note: true tracking accuracy requires manually labeled ground truth. "
        "Without ground truth, this report uses simple indicators: raw ID count, "
        "short tracks, and FPS.",
    ]
    summary_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return metrics_path, summary_path, json_path, tracks_path, chart_path


def main():
    args = parse_args()
    CFG["device"] = args.device
    if str(args.device).lower() == "cpu":
        CFG["require_gpu"] = False
        CFG["allow_cpu_fallback"] = True
    elif args.allow_cpu_fallback:
        CFG["allow_cpu_fallback"] = True

    runtime = _get_runtime_config()
    torch_device = runtime["torch_device"]
    yolo_device = runtime["yolo_device"]
    use_half = runtime["use_half"]

    cap = cv2.VideoCapture(args.video)
    if not cap.isOpened():
        raise RuntimeError(f"Khong mo duoc video: {args.video}")

    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps_src = int(cap.get(cv2.CAP_PROP_FPS)) or 30
    out_width = int(width * args.scale) * 2
    out_height = int(height * args.scale)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    report_dir = Path(args.report_dir)
    report_dir.mkdir(parents=True, exist_ok=True)
    writer = cv2.VideoWriter(
        str(output_path),
        cv2.VideoWriter_fourcc(*"mp4v"),
        fps_src,
        (out_width, out_height),
    )
    if not writer.isOpened():
        raise RuntimeError(f"Khong tao duoc output video: {output_path}")

    show_window = args.show
    if show_window and not os.environ.get("DISPLAY", "").strip():
        show_window = False
        print("[WARN] DISPLAY trong - tat live window.")

    print("=" * 72)
    print("RAW TRACKER COMPARISON: ByteTrack vs BoT-SORT")
    print("=" * 72)
    print(f"[OK] Video: {width}x{height} @ {fps_src}fps")
    print(f"[OK] Output: {output_path}")
    print(f"[OK] Model: {args.model}")
    print(f"[OK] Device: {torch_device}  FP16: {use_half}")
    print(f"[OK] conf={args.conf} iou={args.iou} imgsz={args.imgsz}")

    fps_hist = {"bytetrack": collections.deque(maxlen=30), "botsort": collections.deque(maxlen=30)}
    stats = {
        "bytetrack": TrackerStats("ByteTrack", args.short_track_frames),
        "botsort": TrackerStats("BoT-SORT", args.short_track_frames),
    }
    metric_rows = []
    snapshot_paths = []
    frame_idx = 0

    with tempfile.TemporaryDirectory(prefix="tracker_compare_") as tmp_dir:
        tracker_cfgs = write_tracker_cfgs(tmp_dir)
        print(f"[OK] ByteTrack cfg: {tracker_cfgs['bytetrack']}")
        print(f"[OK] BoT-SORT cfg:  {tracker_cfgs['botsort']}")
        print("-" * 72)

        bytetrack_model = YOLO(args.model)
        botsort_model = YOLO(args.model)
        bytetrack_model.to(torch_device)
        botsort_model.to(torch_device)

        try:
            while cap.isOpened():
                ok, frame = cap.read()
                if not ok:
                    break
                frame_idx += 1

                if args.fixed_order or frame_idx % 2 == 1:
                    t0 = time.perf_counter()
                    byte_result = run_tracker(
                        bytetrack_model,
                        frame,
                        tracker_cfgs["bytetrack"],
                        args,
                        yolo_device,
                        use_half,
                    )
                    byte_dt = time.perf_counter() - t0

                    t0 = time.perf_counter()
                    bot_result = run_tracker(
                        botsort_model,
                        frame,
                        tracker_cfgs["botsort"],
                        args,
                        yolo_device,
                        use_half,
                    )
                    bot_dt = time.perf_counter() - t0
                else:
                    t0 = time.perf_counter()
                    bot_result = run_tracker(
                        botsort_model,
                        frame,
                        tracker_cfgs["botsort"],
                        args,
                        yolo_device,
                        use_half,
                    )
                    bot_dt = time.perf_counter() - t0

                    t0 = time.perf_counter()
                    byte_result = run_tracker(
                        bytetrack_model,
                        frame,
                        tracker_cfgs["bytetrack"],
                        args,
                        yolo_device,
                        use_half,
                    )
                    byte_dt = time.perf_counter() - t0

                byte_tracks = extract_tracks(byte_result)
                bot_tracks = extract_tracks(bot_result)
                stats["bytetrack"].update(frame_idx, byte_tracks, byte_dt)
                stats["botsort"].update(frame_idx, bot_tracks, bot_dt)
                fps_hist["bytetrack"].append(1.0 / max(byte_dt, 1e-6))
                fps_hist["botsort"].append(1.0 / max(bot_dt, 1e-6))

                byte_panel, byte_active = draw_tracks(
                    frame,
                    byte_result,
                    "ByteTrack raw output",
                    frame_idx,
                    float(np.mean(fps_hist["bytetrack"])),
                    stats["bytetrack"].seen_ids,
                )
                bot_panel, bot_active = draw_tracks(
                    frame,
                    bot_result,
                    "BoT-SORT raw output",
                    frame_idx,
                    float(np.mean(fps_hist["botsort"])),
                    stats["botsort"].seen_ids,
                )

                byte_panel = resize_panel(byte_panel, args.scale)
                bot_panel = resize_panel(bot_panel, args.scale)
                combined = np.hstack([byte_panel, bot_panel])
                writer.write(combined)

                byte_fps = float(np.mean(fps_hist["bytetrack"]))
                bot_fps = float(np.mean(fps_hist["botsort"]))
                metric_rows.append({
                    "frame": frame_idx,
                    "bytetrack_active_ids": len(byte_active),
                    "botsort_active_ids": len(bot_active),
                    "bytetrack_unique_ids": len(stats["bytetrack"].seen_ids),
                    "botsort_unique_ids": len(stats["botsort"].seen_ids),
                    "bytetrack_fps_rolling": f"{byte_fps:.3f}",
                    "botsort_fps_rolling": f"{bot_fps:.3f}",
                    "bytetrack_new_id_events": stats["bytetrack"].new_id_events,
                    "botsort_new_id_events": stats["botsort"].new_id_events,
                    "bytetrack_lost_id_events": stats["bytetrack"].lost_id_events,
                    "botsort_lost_id_events": stats["botsort"].lost_id_events,
                    "bytetrack_reappeared_id_events": stats["bytetrack"].reappeared_id_events,
                    "botsort_reappeared_id_events": stats["botsort"].reappeared_id_events,
                    "bytetrack_latency_ms": f"{byte_dt * 1000.0:.3f}",
                    "botsort_latency_ms": f"{bot_dt * 1000.0:.3f}",
                })

                if args.snapshot_interval > 0 and frame_idx % args.snapshot_interval == 0:
                    snapshot_path = report_dir / f"snapshot_frame_{frame_idx:06d}.jpg"
                    cv2.imwrite(str(snapshot_path), combined)
                    snapshot_paths.append(snapshot_path)

                if show_window:
                    cv2.imshow("ByteTrack vs BoT-SORT", combined)
                    if cv2.waitKey(1) & 0xFF in (27, ord("q")):
                        print("\n[STOP] Dung boi nguoi dung.")
                        break

                if frame_idx % 100 == 0:
                    print(
                        f"Frame {frame_idx:5d} | "
                        f"Byte active {len(byte_active):2d}, unique {len(stats['bytetrack'].seen_ids):3d}, "
                        f"fps {float(np.mean(fps_hist['bytetrack'])):5.1f} | "
                        f"BoT active {len(bot_active):2d}, unique {len(stats['botsort'].seen_ids):3d}, "
                        f"fps {float(np.mean(fps_hist['botsort'])):5.1f}"
                    )

                if args.max_frames > 0 and frame_idx >= args.max_frames:
                    break

        except KeyboardInterrupt:
            print("\n[STOP] Ctrl+C.")
        finally:
            cap.release()
            writer.release()
            if show_window:
                cv2.destroyAllWindows()

    print("\n[DONE] Raw tracker comparison saved.")
    print(f"       Output: {output_path}")
    print(f"       Frames: {frame_idx}")
    print(f"       ByteTrack unique raw IDs: {len(stats['bytetrack'].seen_ids)}")
    print(f"       BoT-SORT unique raw IDs:  {len(stats['botsort'].seen_ids)}")
    if frame_idx > 0:
        summary = {
            "video": args.video,
            "output": str(output_path),
            "frames": frame_idx,
            "common_tracker_params": COMMON_TRACKER_PARAMS,
            "botsort_extra_params": BOTSORT_EXTRA_PARAMS,
            "fairness_note": (
                "ByteTrack and BoT-SORT use identical common tracker parameters. "
                "BoT-SORT-only ReID/GMC parameters are enabled as its algorithm-specific features. "
                "Execution order alternates per frame unless --fixed-order is used."
            ),
            "accuracy_note": (
                "True tracking accuracy requires ground-truth labels. Without ground truth, "
                "this report uses ID-stability proxy metrics such as unique IDs, short tracks, "
                "lost/reappeared ID events, and track observed duration."
            ),
            "trackers": {
                "bytetrack": stats["bytetrack"].summary(),
                "botsort": stats["botsort"].summary(),
            },
            "track_lifetimes": (
                stats["bytetrack"].track_rows()
                + stats["botsort"].track_rows()
            ),
            "snapshots": [str(path) for path in snapshot_paths],
        }
        metrics_path, summary_path, json_path, tracks_path, chart_path = write_report_files(
            report_dir, metric_rows, summary
        )
        print(f"       Metrics: {metrics_path}")
        print(f"       Track lifetimes: {tracks_path}")
        print(f"       Summary: {summary_path}")
        print(f"       Summary JSON: {json_path}")
        print(f"       Chart: {chart_path}")


if __name__ == "__main__":
    main()
